import Head from "next/head";
import Image from "next/image";
import Container from "@material-ui/core/Container";
import MovieItem from "../src/components/MovieItem";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div id="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container style={{ maxWidth: 1080 }} fixed>
        <MovieItem />
        <Footer />
      </Container>
    </div>
  );
}

const Footer = () => (
  <footer className={styles.footer}>
    <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
    >
      Powered by{" "}
      <span className={styles.logo}>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
    </a>
  </footer>
);
