import Head from "next/head";
import Image from "next/image";
import Container from "@material-ui/core/Container";
import MovieItem from "../src/components/MovieItem";
import HeroBanner from "../src/components/Banner";
import Header from "../src/components/Header";
import styles from "../styles/Home.module.css";

const sections = [
  { title: "Box Office", url: "#" },
  { title: "Series TV", url: "#" },
  { title: "Animation", url: "#" },
  { title: "Genre", url: "#" },
  { title: "Years", url: "#" },
];

const Footer = () => (
  <footer className={styles.footer}>
    <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
    >
      Powered by{" "}
      <span className={styles.logo}>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
    </a>
  </footer>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Home" sections={sections} />
      <HeroBanner />
      <div id="home">
        <Container style={{ maxWidth: 1080 }} fixed>
          <MovieItem />
          <Footer />
        </Container>
      </div>
    </>
  );
}
