import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import clsx from "clsx";
import Sticky from "react-sticky-el";
import Container from "@material-ui/core/Container";
import { TabCategories } from "../src/components/Tab";
import useScrollTrigger from "@material-ui/core/useScrollTrigger";
import GenreList from "../data/genre.json";
import MovieItem from "../src/components/MovieItem";
import HeroBanner from "../src/components/Banner";
import { NavBar } from "../src/components/Header";
import SearchDialog from "../src/components/SearchDialog";
import styles from "../styles/Home.module.css";

const sections = [
  { title: "Box Office", url: "#" },
  { title: "Series TV", url: "#" },
  { title: "Animation", url: "#" },
  { title: "Genre", url: "#" },
  { title: "Years", url: "#" },
];

const Footer = () => (
  <footer className={styles.footer}>
    <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
    >
      Powered by{" "}
      <span className={styles.logo}>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
    </a>
  </footer>
);

export default function Home() {
  const [isSearchModalVisible, setIsSearchModalVisible] = useState(false);
  const [isBottomNavbarVisible, setIsBottomNavbarVisible] = useState(false);

  const handleClickSearch = () => {
    setIsSearchModalVisible(!isSearchModalVisible);
  };
  const handleClose = () => {
    setIsSearchModalVisible(!isSearchModalVisible);
  };
  const handleShowBottomNavbar = () => {
    setIsBottomNavbarVisible(!isBottomNavbarVisible);
  };
  const trigger = useScrollTrigger({ threshold: 500 });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar onClickSearch={handleClickSearch} position={"static"} showSearchButton={false} />

      <Container style={{ maxWidth: "100vw", padding: 0 }} className="banner-hero" fixed>
        <SearchDialog isVisible={isSearchModalVisible} handleClose={handleClose} />
        <svg className="svg-bg" width="364" height="384" viewBox="0 0 364 384" fill="none">
          <defs>
            <pattern
              id="eab71dd9-9d7a-47bd-8044-256344ee00d0"
              x="0"
              y="0"
              width="20"
              height="20"
              patternUnits="userSpaceOnUse"
            >
              <rect x="0" y="0" width="4" height="4" fill="currentColor"></rect>
            </pattern>
          </defs>
          <rect width="364" height="384" fill="url(#eab71dd9-9d7a-47bd-8044-256344ee00d0)"></rect>
        </svg>
        <HeroBanner />
      </Container>

      <div id="home">
        <Sticky stickyStyle={{ zIndex: 100, backgroundColor: "#121212" }}>
          <NavBar visible={isBottomNavbarVisible} onClickSearch={handleClickSearch} position={"static"} />
          <Container className={clsx(isSearchModalVisible && "blurred")} style={{ maxWidth: 1080 }} fixed>
            <TabCategories list={GenreList.genres} />
          </Container>
        </Sticky>
        <Container className={clsx(isSearchModalVisible && "blurred")} style={{ maxWidth: 1080 }} fixed>
          <MovieItem />
          <Footer />
        </Container>
      </div>
    </>
  );
}
